destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/writing-pdf"
port: 4010
product: Writing portfolio
print_title: Writing portfolio
print_subtitle: 
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: writing_sidebar
