destination: _site/
url: "http://127.0.0.1:4012"
baseurl: "/design-pdf"
port: 4012
product: product2
print_title: Design portfolio
print_subtitle: 
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: design_sidebar
