source "https://rubygems.org"

# 1. The GitHub Pages environment (Locks Jekyll to v3.9)
gem "github-pages", group: :jekyll_plugins

# 2. The Remote Theme plugin (For hosting on GitHub)
gem "jekyll-remote-theme"

# 3. The Local Theme files (So you can use @import locally)
gem "just-the-docs"

# 4. SEO Tags
gem "jekyll-seo-tag"
